### PR TITLE
Bug 2087042: Rebase cloud-provider-vsphere 15.06.2022

### PR DESCRIPTION
**Pull request by lobziik**
This PR rebases the cloud-provider-vsphere openshift patches on top of the kubernetes/cloud-provider-vsphere master branch after bump dependencies to kube v1.24.1 release.

There are several commits that we carry on top of the upstream cloud-provider-vsphere and the rebase process allows us to preserve those. Here is a description of the process I used to create this PR.

(replicated old @elmiko's process within openshift/kubernetes-autoscaler)

Process

First we need to identify the carry commits that we currently have, this is done against our previous rebase (or fork in this case) to catch new changes. Once identified we will drop commits which have merged upstream and only carry unique commits. (see below for the carried and dropped commits).

Identify carry commits:

```
git log --oneline --no-merges 556ede7f720b9cc91c22b23b360b6156a1824b29..openshift/master
```

where `556ede` is the last upstream commit in our fork. This is the
list of commits we will need to apply onto the new upstream version of the
cloud-provider-vsphere. ideally, some of these commits can be dropped.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch. The following commands cover these steps:

```
$ git remote update # make sure we update our refs
$ git checkout 619502ff4276c345966584bb1f412157385ba7c0 # last commit in upstream master
$ git checkout -b merge-tmp # create a temporary branch for our merge commit
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge kubernetes/cloud-provider-vsphere 15-06-2022 ' | git commit-tree rebase-tmp^{tree} -p HEAD -p merge-tmp -F - # create a new merge commit for our history
fdce34cafdcb91f3dad263eb624ca02150c21b5f # id of new merge commit
$ git branch merge-15-06-2022 fdce34cafdcb91f3dad263eb624ca02150c21b5f # create a new branch for the cherry-pick work
$ git checkout merge-15-06-2022
$ git cherry-pick <carry commits> # cherry pick the needed commits into the new branch
```
With the `merge-15-06-2022` branch in place, I cherry picked the carry commits which we should carry.

Commits to carry:

These commits are integral to our CI platform, or are specific to the releases we create for OpenShift.

```
afd0d591 UPSTREAM: <carry>: Run unit tests from pkg folder only
0400604f UPSTREAM: <carry>: Use golang 1.17 to build the component image
bb9b2a3f UPSTREAM: <carry>: Updating and vendoring go modules after an upstream rebase
b3d92d73 UPSTREAM: <carry>: disable staticcheck for OpenShift CI
e965bd94 UPSTREAM: <carry>: Add .ci-operator.yaml file
f4a86607 UPSTREAM: <carry>: fix staticcheck cache in openshift ci
8898a862 UPSTREAM: <carry>: Add vendored dependencies (vendor)
34e82d18 UPSTREAM: <carry>: Remove /vendor folder from .gitignore
d3a5bdc9 UPSTREAM: <carry>: OCP specific build scripts and Dockerfile
eba378c1 UPSTREAM: <carry>: rm OWNERS_ALIASES and upd OWNERS
```

Changes in commits:

```
b3d92d73 UPSTREAM: <carry>: disable staticcheck for OpenShift CI
f4a86607 UPSTREAM: <carry>: fix staticcheck cache in openshift ci
d3a5bdc9 UPSTREAM: <carry>: OCP specific build scripts and Dockerfile
```

Commits above was squashed into a single commit: `1fc9db07 UPSTREAM: <carry>: OCP specific build scripts and Dockerfile`

Commit with dependencies vendoring was added on top of all.

### CODE REVIEW

**Comment by elmiko** [comment]
@lobziik following on from our discussion today, i think it would be nice to note in the description the commit you are adding and what it's fixing.

**Comment by lobziik** [comment]
@elmiko - this required more work around than i expected, i will create a follow up pr with envtest update. Lets leave just rebase and revendoring here.

**Comment by elmiko** [comment]
ack, thanks for the update @lobziik

**Review by elmiko — COMMENTED** [review]
this generally looks correct to me
/lgtm

**Pull request merged**
