### PR TITLE
OCPBUGS-1413: Rebase 13.10.2022 k8s 1.25

### PR DESCRIPTION
**Pull request by lobziik**
This PR rebases the cloud-provider-vsphere openshift patches on top of the kubernetes/cloud-provider-vsphere master branch after kubernetes dependencies to v1.25.2 update.
There are several commits that we carry on top of the upstream cloud-provider-vsphere and the rebase process allows us to preserve those. Here is a description of the process I used to create this PR.

(replicated @elmiko's process within openshift/kubernetes-autoscaler)

## Process

First we need to identify the carry commits that we currently have, this is done against our previous rebase (or fork in this case) to catch new changes. Once identified we will drop commits which have merged upstream and only carry unique commits. (see below for the carried and dropped commits).

Identify carry commits:

```
git log --oneline --no-merges 619502ff4276c345966584bb1f412157385ba7c0..openshift/master
```

where `619502` is the last upstream commit in our fork. This is the
list of commits we will need to apply onto the new upstream version of the
cloud-provider-vsphere. ideally, some of these commits can be dropped.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch. The following commands cover these steps:

```
$ git remote update # make sure we update our refs
$ git checkout 138e46b840781db280d8cdd0651a6455061fbfc6 # master branch head after update dependencies to 1.25
$ git checkout -b merge-tmp # create a temporary branch for our merge commit
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge kubernetes/cloud-provider-vsphere 13-10-2022 ' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F - # create a new merge commit for our history
6fccf6070b603d6c3afd815c0184484a403b0721 # id of new merge commit
$ git branch merge-13-10-2022 6fccf6070b603d6c3afd815c0184484a403b0721 # create a new branch for the cherry-pick work
$ git checkout merge-13-10-2022
$ git cherry-pick <carry commits> # cherry pick the needed commits into the new branch
```
With the `merge-13-10-2022` branch in place, I cherry picked the carry commits which we should carry.

### Carried Commits

These commits are integral to our CI platform, or are specific to the releases we create for OpenShift.

```
375c8a54 Updating ose-vsphere-cloud-controller-manager images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/b44f15ec9e84d1831eac81f8c757b3bed985dbeb/images/ose-vsphere-cloud-controller-manager.yml
52f8e1f2 UPSTREAM: <carry>: fix .dockerignore to satisfy OCP specific requirements
8dad25e2 UPSTREAM: <carry>: delete .github directory
a3516c75 UPSTREAM: <carry>: Add OCP specific exclusion to the .dockerignore
b4b83280 Updating ose-vsphere-cloud-controller-manager images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/2e5eba0108299087402c119ba0dc979a0a6c0bd1/images/ose-vsphere-cloud-controller-manager.yml
c7ac93a5 UPSTREAM: <carry>: Updating and vendoring go modules after an upstream rebase
d28c231f UPSTREAM: <carry>: Use golang 1.17 to build the component image
1bc4e1cb UPSTREAM: <carry>: Updating and vendoring go modules after an upstream rebase
1383b547 UPSTREAM: <carry>: Add .ci-operator.yaml file
0b36befb UPSTREAM: <carry>: Add vendored dependencies (vendor)
d07a1783 UPSTREAM: <carry>: Remove /vendor folder from .gitignore
63375c66 UPSTREAM: <carry>: OCP specific build scripts and Dockerfile
d81b6072 UPSTREAM: <carry>: rm OWNERS_ALIASES and upd OWNERS
c1ae7ee4 Updating ose-vsphere-cloud-controller-manager images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/5bdff8f034891d949f702da1c194719005a2df3a/images/ose-vsphere-cloud-controller-manager.yml
```

### Dropped Commits

```
375c8a54 Updating ose-vsphere-cloud-controller-manager images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/b44f15ec9e84d1831eac81f8c757b3bed985dbeb/images/ose-vsphere-cloud-controller-manager.yml
b4b83280 Updating ose-vsphere-cloud-controller-manager images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/2e5eba0108299087402c119ba0dc979a0a6c0bd1/images/ose-vsphere-cloud-controller-manager.yml
c7ac93a5 UPSTREAM: <carry>: Updating and vendoring go modules after an upstream rebase
d28c231f UPSTREAM: <carry>: Use golang 1.17 to build the component image
1bc4e1cb UPSTREAM: <carry>: Updating and vendoring go modules after an upstream rebase
0b36befb UPSTREAM: <carry>: Add vendored dependencies (vendor)
c1ae7ee4 Updating ose-vsphere-cloud-controller-manager images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/5bdff8f034891d949f702da1c194719005a2df3a/images/ose-vsphere-cloud-controller-manager.yml
```

All vendor related commints was dropped, vendoring was done in separate commit on top of all after rebase

### Changed Commits

1. All ART commits with dockerfile updates was squashed into one
2. .dockerignore related commits (`a3516c75`, `52f8e1f2`) was squashed into one = `d7af79e2`
3. `1383b547` commit with .ci-operator.yaml was updated to reflect fresh versions
4. `63375c66` was changed with removal of "go-get-tool.sh" and replace it with `go install`

### Added Commits

1. `008697e9 UPSTREAM: <drop>: Updating and vendoring go modules after an upstream rebase`

### Result
Resulting commits after squashes and other changes:

```
008697e9 UPSTREAM: <drop>: Updating and vendoring go modules after an upstream rebase
fc244fcf UPSTREAM: <carry>: Updating ose-vsphere-cloud-controller-manager images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/b44f15ec9e84d1831eac81f8c757b3bed985dbeb/images/ose-vsphere-cloud-controller-manager.yml
b5aca4bd UPSTREAM: <carry>: delete .github directory
d7af79e2 UPSTREAM: <carry>: fix .dockerignore to satisfy OCP specific requirements
4b30fe94 UPSTREAM: <carry>: Add .ci-operator.yaml file
32e7a93c UPSTREAM: <carry>: Remove /vendor folder from .gitignore
78ef92a5 UPSTREAM: <carry>: OCP specific build scripts and Dockerfile
d7babcb1 UPSTREAM: <carry>: rm OWNERS_ALIASES and upd OWNERS
```

### CODE REVIEW

**Comment by lobziik** [comment]
https://github.com/openshift/release/pull/33100 - this need to go first.

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by lobziik** [comment]
Updated go-get-tool.sh script, "go get" behaviour was changed in 1.18, it's no longer build binary

**Pull request merged**
